# Platform version to build against
platform :ios, '11.0'

use_frameworks!

target 'RSocketSwift_Example' do
  pod 'RSocketSwift', :path => '../'

  target 'RSocketSwift_Tests' do
    inherit! :search_paths

    
  end
end
