name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-on-macOS-and-iOS:
    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
        
#    - name: Test on iOS Simulator
#      run: >
#        xcodebuild test
#        -scheme RSocket-Package
#        -parallelizeTargets
#        -skip-testing:RSocketCorePerformanceTests
#        -parallel-testing-enabled
#        -sdk:iphonesimulator
#        -destination:'platform=iOS Simulator,name=iPhone 12'
        
    - name: Test on macOS
      run: >
        swift test
        --parallel
        --enable-test-discovery
        --filter="^((?!(Performance)).)*\..*$"
        
  performance-tests-on-macOS:
    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - name: Build & Run Performance Tests on macOS
      run: >
        swift test
        --configuration=release
        --enable-test-discovery
        --filter="^.*(Performance).*\..*"
    
  test-on-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test on Linux
      # filter regex excludes all tests targets which contain the word "Performance" in their name
      run: >
        swift test
        --parallel
        --enable-test-discovery
        --filter="^((?!(Performance)).)*\..*$"
        
    - name: Build & Run Performance Tests on Linux
      run: >
        swift test
        --configuration=release
        --enable-test-discovery
        --filter="^.*(Performance).*\..*"
