name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
          
  tests:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - name: Build & Run Tests (without performance tests)
      # filter regex excludes all tests targets which contain the word "Performance" in their name
      run: >
        swift test
        -v
        --parallel
        --enable-test-discovery
        --sanitize=thread
        --filter="^((?!(Performance)).)*\..*$"
  performance-tests:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - name: Build & Run Performance Tests
      # filter regex includes only test targets which contain the word "Performance" in their name
      # build with optimisation enabled
      run: >
        swift test
        -Xswiftc="-O"
        --enable-test-discovery
        --filter="^.*(Performance).*\..*"
