name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-on-macOS-and-iOS:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 12.5.1
    - name: Test on iOS Simulator
      run: >
        xcodebuild test
        -scheme RSocket-Package
        -parallelizeTargets
        -skip-testing:RSocketCorePerformanceTests
        -parallel-testing-enabled
        -sdk:iphonesimulator
        -destination:'platform=iOS Simulator,name=iPhone 12'
        
    - name: Test on macOS
      run: >
        xcodebuild test
        -scheme RSocket-Package
        -parallelizeTargets
        -skip-testing:RSocketCorePerformanceTests
        -parallel-testing-enabled
        -destination 'platform=macOS'

  test-on-macOS-with-Xcode-13-Beta:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 13.0
        
    - name: Test on macOS
      run: swift test
        
  performance-tests-on-macOS:
    runs-on: macos-11
    strategy:
      matrix:
        xcode: ['12.5.1', '13.0']

    steps:
    - uses: actions/checkout@v2
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ matrix.xcode }}
    - name: Build & Run Performance Tests on macOS
      run: >
        swift test
        --configuration=release
        --enable-test-discovery
        --filter="^.*(Performance).*\..*"
    
  test-on-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test on Linux
      # filter regex excludes all tests targets which contain the word "Performance" in their name
      run: >
        swift test
        --parallel
        --enable-test-discovery
        --filter="^((?!(Performance)).)*\..*$"
        
    - name: Build & Run Performance Tests on Linux
      run: >
        swift test
        --configuration=release
        --enable-test-discovery
        --filter="^.*(Performance).*\..*"
