name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests (without performance tests)
      # filter regex excludes all tests targets which contain the word "Performance" in their name
      run: swift test -v --filter="^((?!(Performance)).)*\..*$"
  performance-tests:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build & Run Performance Tests
      # filter regex includes only test targets which contain the word "Performance" in their name
      # build with optimisation enabled
      run: swift test --filter="^.*(Performance).*\..*" -Xswiftc="-O"
