name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-macOS:
    strategy:
      matrix:
        platform: [macos-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - name: Test on macOS
      run: >
        xcodebuild test
        -scheme RSocket-Package
        -parallelizeTargets
        -skip-testing:RSocketCorePerformanceTests
        -parallel-testing-enabled
        -destination 'platform=macOS'
        
    - name: Test on iOS Simulator
      run: >
        xcodebuild test
        -scheme RSocket-Package
        -parallelizeTargets
        -parallel-testing-enabled
        -skip-testing:RSocketCorePerformanceTests
        -sdk iphonesimulator
        -destination 'platform=iOS Simulator,name=iPhone 12'
        
    - name: Build & Run Performance Tests on macOS
      run: >
        xcodebuild test
        -scheme RSocketCore
        -configuration Release
        -only-testing:RSocketCorePerformanceTests
        -destination 'platform=macOS'
  build-linux:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - name: Test on Linux
      if: runner.os == 'Linux'
      # filter regex excludes all tests targets which contain the word "Performance" in their name
      run: >
        swift test
        -v
        --parallel
        --enable-test-discovery
        --filter="^((?!(Performance)).)*\..*$"
        
    - name: Build & Run Performance Tests on Linux
      if: runner.os == 'Linux'
      run: >
        swift test
        -Xswiftc="-O"
        --enable-test-discovery
        --filter="^.*(Performance).*\..*"
